version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "20:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: org.springframework.cloud:spring-cloud-dependencies
        versions:
          - ">= 2023"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
