stages:
  - build
  - test
  - sync

build:mvn:
  stage: build
  image: xuxiaoweicomcn/maven-mysql-client:3.6.3-jdk-8
  services:
    - mysql:8.0.36
  variables:
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
      --no-transfer-progress
      -DinstallAtEnd=true
      -DdeployAtEnd=true
    MYSQL_DATABASE: nacos
    MYSQL_ROOT_PASSWORD: nacos
    XUXIAOWEI_NACOS_MYSQL_IP: mysql
    XUXIAOWEI_NACOS_MYSQL_USERNAME: root
    XUXIAOWEI_NACOS_MYSQL_DATABASE: nacos
  before_script:
    - if [ $CI_SERVER_HOST == 'gitlab.helm.xuxiaowei.cn' ]; then
      sleep 20s;
      fi
    - mysql -u root -p${MYSQL_ROOT_PASSWORD} --host=mysql ${MYSQL_DATABASE} < sql/1-nacos-mysql-schema.sql
    - mysql -u root -p${MYSQL_ROOT_PASSWORD} --host=mysql ${MYSQL_DATABASE} < sql/2-nacos-mysql-data.sql
  script:
    - mvn -v
    - mvn clean package -U -pl nacos -DskipTests=false -s settings.xml
    - nohup java -jar nacos/target/nacos-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
    - sleep 15s
    - cat nohup.out
    - curl "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=blur" && echo
    - cat nohup.out
    - >-
      mvn clean package -U
      -pl spring-cloud-xuxiaowei-passport
      -pl spring-cloud-xuxiaowei-commons/spring-cloud-xuxiaowei-commons-core
      -pl spring-cloud-xuxiaowei-commons/spring-cloud-xuxiaowei-commons-loadbalancer
      -DskipTests=false -s settings.xml
    - nohup java -jar spring-cloud-xuxiaowei-passport/target/spring-cloud-xuxiaowei-passport-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
    - sleep 10s
    - mvn clean package -U -pl !nacos,!spring-cloud-xuxiaowei-passport -DskipTests=false -s settings.xml
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .m2/repository
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:mvnw:
  stage: build
  image: xuxiaoweicomcn/openjdk-mysql-client:8
  services:
    - mysql:8.0.36
  variables:
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
      --no-transfer-progress
      -DinstallAtEnd=true
      -DdeployAtEnd=true
    MYSQL_DATABASE: nacos
    MYSQL_ROOT_PASSWORD: nacos
    XUXIAOWEI_NACOS_MYSQL_IP: mysql
    XUXIAOWEI_NACOS_MYSQL_USERNAME: root
    XUXIAOWEI_NACOS_MYSQL_DATABASE: nacos
  before_script:
    - if [ $CI_SERVER_HOST == 'gitlab.helm.xuxiaowei.cn' ]; then
      sleep 20s;
      fi
    - mysql -u root -p${MYSQL_ROOT_PASSWORD} --host=mysql ${MYSQL_DATABASE} < sql/1-nacos-mysql-schema.sql
    - mysql -u root -p${MYSQL_ROOT_PASSWORD} --host=mysql ${MYSQL_DATABASE} < sql/2-nacos-mysql-data.sql
  script:
    - chmod +x mvnw
    - ./mvnw -v
    - ./mvnw clean package -U -pl nacos -DskipTests=false -s settings.xml
    - nohup java -jar nacos/target/nacos-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
    - sleep 15s
    - cat nohup.out
    - curl "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=&group=&appName=&config_tags=&pageNo=1&pageSize=10&tenant=&search=blur" && echo
    - cat nohup.out
    - >-
      ./mvnw clean package -U
      -pl spring-cloud-xuxiaowei-passport
      -pl spring-cloud-xuxiaowei-commons/spring-cloud-xuxiaowei-commons-core
      -pl spring-cloud-xuxiaowei-commons/spring-cloud-xuxiaowei-commons-loadbalancer
      -DskipTests=false -s settings.xml
    - nohup java -jar spring-cloud-xuxiaowei-passport/target/spring-cloud-xuxiaowei-passport-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
    - sleep 10s
    - ./mvnw clean package -U -pl !nacos,!spring-cloud-xuxiaowei-passport -DskipTests=false -s settings.xml
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .m2/repository
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $MVNW == "true"

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - /sync.yml

gemnasium-maven-dependency_scanning:
  rules:
    - changes:
        - pom.xml
        - "**/pom.xml"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DEPENDENCY_SCANNING == "true"
