stages:
  - build
  - test

build:mvn:
  stage: build
  image: maven:3-openjdk-8
  variables:
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
      --no-transfer-progress
      -DinstallAtEnd=true
      -DdeployAtEnd=true
  script:
    - mvn -v
    - mvn clean package -U -pl nacos -DskipTests=false -s settings.xml
    - nohup java -jar nacos/target/nacos-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
    - sleep 10s
    - >-
      mvn clean install -U 
      -pl spring-cloud-xuxiaowei-commons/spring-cloud-xuxiaowei-commons-core
      -pl spring-cloud-xuxiaowei-commons/spring-cloud-xuxiaowei-commons-loadbalancer
    - mvn clean package -U -pl spring-cloud-xuxiaowei-passport -DskipTests=false -s settings.xml
    - nohup java -jar spring-cloud-xuxiaowei-passport/target/spring-cloud-xuxiaowei-passport-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
    - sleep 10s
    - mvn clean package -U -pl !nacos,!spring-cloud-xuxiaowei-passport -DskipTests=false -s settings.xml
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .m2/repository
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:mvnw:
  stage: build
  image: openjdk:8
  variables:
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
      --no-transfer-progress
      -DinstallAtEnd=true
      -DdeployAtEnd=true
  script:
    - chmod +x mvnw
    - ./mvnw -v
    - ./mvnw clean package -U -pl nacos -DskipTests=false -s settings.xml
    - nohup java -jar nacos/target/nacos-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
    - sleep 10s
    - >-
      ./mvnw clean install -U 
      -pl spring-cloud-xuxiaowei-commons/spring-cloud-xuxiaowei-commons-core
      -pl spring-cloud-xuxiaowei-commons/spring-cloud-xuxiaowei-commons-loadbalancer
    - ./mvnw clean package -U -pl spring-cloud-xuxiaowei-passport -DskipTests=false -s settings.xml
    - nohup java -jar spring-cloud-xuxiaowei-passport/target/spring-cloud-xuxiaowei-passport-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
    - sleep 10s
    - ./mvnw clean package -U -pl !nacos,!spring-cloud-xuxiaowei-passport -DskipTests=false -s settings.xml
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .m2/repository
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $MVNW == "true"

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml

gemnasium-maven-dependency_scanning:
  rules:
    - changes:
        - pom.xml
        - "**/pom.xml"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $DEPENDENCY_SCANNING == "true"
