# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      MYSQL_DATABASE: nacos
      MYSQL_ROOT_PASSWORD: nacos
      XUXIAOWEI_NACOS_MYSQL_DATABASE: nacos

    services:
      mysql:
        image: mysql:8.0.36
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL
        run: |
          sleep 10
          until docker exec $(docker ps -qf "ancestor=mysql:8.0.36") mysqladmin ping --silent; do
              echo 'Waiting for MySQL to be available...'
              sleep 10
          done
          sleep 10

      - name: Set ENV
        shell: sh
        run: |
          docker ps
          echo "XUXIAOWEI_NACOS_MYSQL_IP=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -qf 'ancestor=mysql:8.0.36')`" >> $GITHUB_ENV
          echo ${{ env.XUXIAOWEI_NACOS_MYSQL_IP }}

      - name: Get ENV
        shell: sh
        run: |
          echo ${{ env.XUXIAOWEI_NACOS_MYSQL_IP }}

      - name: Init MySQL
        run: |
          mysql --version
          mysql -u root -p${{ env.MYSQL_ROOT_PASSWORD }} --host=${{ env.XUXIAOWEI_NACOS_MYSQL_IP }} ${{ env.XUXIAOWEI_NACOS_MYSQL_DATABASE }} < sql/1-nacos-mysql-schema.sql
          mysql -u root -p${{ env.MYSQL_ROOT_PASSWORD }} --host=${{ env.XUXIAOWEI_NACOS_MYSQL_IP }} ${{ env.XUXIAOWEI_NACOS_MYSQL_DATABASE }} < sql/2-nacos-mysql-data.sql

      - name: Java version
        run: java -version

      - name: Maven version
        run: mvn -v

      - name: Build with Maven
        run: mvn clean package -U
